### ISSUE TITLE
Feature Request: Redirect aliases to primary domain

### ISSUE THREAD

**Issue by dotsam** [AnoopAlias/XtendWeb#115]
Hi Anoop,

I took a look at the work you're doing for nDeploy v4, and it all looks great. I'm happy to see more options that can be enabled without a completely new template, like wwwredirect and hsts. One more thing I'd like to see here is redirecting all aliases of a domain to the primary domain. I currently maintain versions of templates that do and do not do this, so having this as a GUI option would be a huge help to me.

This is my current implementation of this (adapted to use the new jina2 variables), and is used to redirect any alias or with-www domain to the primary domain.

```
if ($host != '{{ MAINDOMAINNAME }}') {
    return 301 $scheme://{{ MAINDOMAINNAME }}$request_uri;
}
```

I know the conventional wisdom in nginx is "if is evil", but when only doing returns or rewrites with it, there shouldn't be any issues. You could also implement this for the wwwredirect option instead of a separate `server` section, as I would think that may be more resource intensive for nginx with a large number of domains?

**Comment by AnoopAlias** [comment]
@dotsam - Sure let me check how this can be done. Please do check the rest of the code in the ndeploy4 branch and let me know changes/feedback/suggestions etc . Thanks.
